import { afterEach, expect, it, vi } from 'vitest';
vi.mock('../db.js', () => ({ getAutoPrintEnabledConfigs: vi.fn(), getMarketplaceAccountsForUser: vi.fn(), updateAutoPrintLastPolled: vi.fn(), addPrintQueueJob: vi.fn(), addPdfPrintQueueJob: vi.fn(), getQueuedShipmentIds: vi.fn(), releaseStaleJobs: vi.fn(), markStaleAgentsOffline: vi.fn(), getUnprocessedMLNotifications: vi.fn() }));
vi.mock('../jobs/withJobLock.js', () => ({ withJobLock: vi.fn(async (_key, run) => run()) }));
vi.mock('../providers/index.js', () => ({ getProvider: vi.fn() }));
vi.mock('../services/accounts.js', () => ({ getFreshAccountContext: vi.fn() }));
vi.mock('../routes/notifications.js', () => ({ reprocessNotificationRow: vi.fn() }));
vi.mock('../services/shopeeArrange.js', () => ({ arrangeReadyShipments: vi.fn(), ensureDocumentsForArranged: vi.fn() }));
import * as db from '../db.js';
import { getProvider } from '../providers/index.js';
import { getFreshAccountContext } from '../services/accounts.js';
import { arrangeReadyShipments } from '../services/shopeeArrange.js';
import { withJobLock } from '../jobs/withJobLock.js';
import { startAutoPrintPoller } from '../jobs/autoPrintPoller.js';
afterEach(() => { vi.clearAllTimers(); vi.useRealTimers(); vi.resetAllMocks(); });
it('separates Shopee 60s and ML 5min locks; arrange-only never auto-prints', async () => {
  vi.useFakeTimers();
  vi.mocked(db.getAutoPrintEnabledConfigs).mockImplementation(async include => include ? [{ user_id: 1, enabled: false }] : [{ user_id: 1, enabled: true }]);
  vi.mocked(db.getUnprocessedMLNotifications).mockResolvedValue([]);
  vi.mocked(db.getMarketplaceAccountsForUser).mockResolvedValue([{ id: 1, provider: 'shopee', auto_arrange_shipment: true, arrange_method: 'dropoff' }, { id: 2, provider: 'mercadolivre' }] as any);
  const ml = vi.fn(async () => []); const shopee = vi.fn(async () => []);
  vi.mocked(getProvider).mockImplementation(id => id === 'shopee' ? { listAutoPrintableShipmentIds: shopee } as any : { getLabelsZPL: vi.fn(), listPrintableShipmentIds: ml } as any);
  vi.mocked(getFreshAccountContext).mockResolvedValue({ accessToken: 'test', externalUserId: 's' } as any);
  vi.mocked(db.getQueuedShipmentIds).mockResolvedValue(new Set());
  vi.mocked(arrangeReadyShipments).mockResolvedValue({ arranged: 0, failed: 0, skipped: 0 });
  startAutoPrintPoller(); await vi.advanceTimersByTimeAsync(0);
  expect(ml).toHaveBeenCalledTimes(1); expect(arrangeReadyShipments).toHaveBeenCalledTimes(1); expect(shopee).not.toHaveBeenCalled();
  await vi.advanceTimersByTimeAsync(60_000);
  expect(ml).toHaveBeenCalledTimes(1); expect(arrangeReadyShipments).toHaveBeenCalledTimes(2);
  expect(new Set(vi.mocked(withJobLock).mock.calls.map(c => c[0])).size).toBe(2);
  await vi.advanceTimersByTimeAsync(240_000); expect(ml).toHaveBeenCalledTimes(2);
});
